# Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

# Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [22]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [23]:
a_centered.shape

(5, 2)

# Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [24]:
a_centered_sp = a_centered[0,0] * a_centered[0,1] + a_centered[1,0] * a_centered[1,1] + a_centered[2,0] * a_centered[2,1] + a_centered[3,0] * a_centered[3,1] + a_centered[4,0] * a_centered[4,1]

a_centered_sp

8.0

In [25]:
at = a_centered.transpose()[:1, :]
at

array([[-1.,  0.,  1.,  1., -1.]])

In [26]:
a_centered_sp = np.dot(at, a_centered[:,1:])
a_centered_sp


array([[8.]])

In [27]:
for N in range(2,10):       
    a_centered_div = a_centered_sp / (N - 1)
    print(f'При N = {N} равно: {a_centered_div}')


При N = 2 равно: [[8.]]
При N = 3 равно: [[4.]]
При N = 4 равно: [[2.66666667]]
При N = 5 равно: [[2.]]
При N = 6 равно: [[1.6]]
При N = 7 равно: [[1.33333333]]
При N = 8 равно: [[1.14285714]]
При N = 9 равно: [[1.]]
